const northNames = [
  "Kelly Rirgan",
  "R.S Tiatok family",
  "Tristen Stone & Cooper",
  "Crawford",
  "Croan Latl",
  "D.J Nulpel",
  "Aaron",
  "Stark Gallahger",
  "Tory Miller",
  "Emily Lancaster",
  "Ted Bloe",
  "Micheal Hollieb",
  "Satker Mellins",
  "Courtney Swinson",
  "Hunter Frostik",
  "Anne Weinherg",
  "Sean Sweewy",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
  "Unreadable",
];

export default northNames;
