const northNames = [
  "Kelly Rirgan",
  "R.S Tiatok family",
  "Tristen Stone & Cooper",
  "Crawford",
  "Croan Latl",
  "D.J Nulpel",
  "Aaron",
  "Stark Gallahger",
  "Tory Miller",
  "Emily Lancaster",
  "Ted Bloe",
  "Micheal Hollieb",
  "Satker Mellins",
  "Courtney Swinson",
  "Hunter Frostik",
  "Anne Weinherg",
  "Sean Sweewy",
  "Baurice W.",
  "Hailey Inge",
  "Katie Chirrco",
  "Trent Tupwiler",
  "Jessica Dymon",
  "Grace",
  "Kevin Daniel",
  "Abigail Naughton",
  "Priya",
  "Kyle Dixon",
  "Michael C. Johnson",
  "Class of 2015",
  "Unreadable",
  "Unreadable",
  "Sydney Marks",
  "Colleen Dietrck",
  "First Athletic Director",
  "Ransum",
  "Toony",
  "Paul Singh",
  "Tracie Weston",
  "Unreadable",
  "Ann Spivey",
  "Unreadable",
  "Nicole Andese",
  "Zach Johnson",
  "Hannah Moore",
  "Jakie Craven",
  "Linga McBride",
  "Kennedy Family",
  "Ashcyn",
  "Kameron Simms",
  "Floyd Johnson",
  "Heid Pass",
  "Yanioa Family",
  "Kevin Hander",
  "Noah  Carpenter",
  "Dr Gwen Miller",
  "Hongring Jamie Mears",
  "Kathryn Nagasawa",
  "Unreadable",
  "Michael Bliss",
  "Gan Gihls",
  "Conrad Faett",
  "Specialty Center",
  "Rhys Caplinger",
  "Brittany McGuire",
  "Brooke Simms",
];

export default northNames;
