const eastNames = [
  "Chelsie H Blunt",
  "Rarbara Kloecker PTSA Charter",
  "Amanda Clevenger",
  "Denise Russell",
  "Cindy Richardson PSTA Charter",
  "Ethan Mading",
  "Cameron Mitten",
  "Conner Murray",
  "Depaul Btraub",
  "Evan Alston",
  "Mason Steinruck",
  "Anne Christian",
  "John Woodburn",
  "Gary Natoli",
  "Jacob Pruden",
  "Justus Snead",
  "Brian Craven",
  "Daniel Lythgoe",
  "Sydney Caplinger",
  "THINK",
  "Bryce C. White",
  "Garrett Family",
  "Aaron Natoli",
  "Ambrianna N Fbeeze",
  "Roll Teali",
  "Crytzer Family",
  "Jeanette V Kuhn",
  "Anthony Charles Clark",
  "D Angelo Brown",
  "Georgia Elizabeth Clark",
  "Elle Caplinger",
  "The Young Girls",
  "Ryan McGuire",
  "JP WIlliams",
  "Haley Mayers",
  "Perry E. Scott",
  "Olivia Walker",
  "Summer Lawson",
  "John Barker Davis",
  "Chase Ingram",
  "Ashley Wilson",
  "Hyman Family",
  "Britlyn Weinstock",
  "Kaelie Jager",
  "John Machowa",
  "Hidden Canije",
  "Soham Apte",
  "Justine Jordan",
  "Nick Parrish",
  "Unreadable",
  "Victoria Walker",
  "Brittany Roland",
  "Ingrid Johnson",
  "Brittany Bolton-scott",
  "Grey Caplinger",
  "Mary beth trice",
  "Hillary Rose Meacham",
  "Christopher Walker",
  "Cameron Leonard",
  "Sydney Banton",
];

export default eastNames;
